'use strict';
const $=s=>document.querySelector(s), KEY='tenran-techo-v1', data=window.EXHIBITIONS;
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let saved={favorites:[],records:{}},tab='all',editing=null;
function valid(x){return x&&Array.isArray(x.favorites)&&x.favorites.every(v=>typeof v==='string')&&x.records&&typeof x.records==='object'&&!Array.isArray(x.records)&&Object.values(x.records).every(r=>r&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&typeof r.note==='string'&&r.note.length<=5000)}
try{const x=JSON.parse(localStorage.getItem(KEY));if(valid(x))saved=x}catch{}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));saved=next;render();return true}catch{toast('保存できませんでした。ブラウザの保存設定をご確認ください。');return false}}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const date=today(), region=$('#region').value, period=$('#period').value, day=$('#day').value,q=$('#query').value.trim().toLowerCase();const list=data.filter(e=>{if(tab==='favorites'&&!saved.favorites.includes(e.id))return false;if(tab==='records'&&!saved.records[e.id])return false;if(region==='関西'&&!['兵庫','大阪','京都'].includes(e.region))return false;if(region==='その他'&&['兵庫','大阪','京都'].includes(e.region))return false;if(region&&!['関西','その他'].includes(region)&&e.region!==region)return false;if(period==='active'&&e.end<date)return false;if(period==='now'&&(e.start>date||e.end<date))return false;if(period==='soon'&&e.start<=date)return false;if(day&&(e.start>day||e.end<day))return false;return (e.title+e.museum).toLowerCase().includes(q)}).sort((a,b)=>a[$('#sort').value].localeCompare(b[$('#sort').value]));$('#heading').textContent={all:'展覧会との出会い',favorites:'行きたい展覧会',records:'わたしの鑑賞記録'}[tab];$('#count').textContent=list.length+' 件';$('#fav-count').textContent=saved.favorites.length;$('#record-count').textContent=Object.keys(saved.records).length;$('#empty').hidden=!!list.length;$('#grid').innerHTML=list.map((e,i)=>{const fav=saved.favorites.includes(e.id),r=saved.records[e.id];return `<article class="card"><div class="poster" style="--bg:${e.bg};--fg:${e.fg}"><span class="number">${esc(e.region)} / EXHIBITION</span><h3>${esc(e.short).replace(/\n/g,'<br>')}</h3><small>展覧手帖 ORIGINAL DESIGN</small></div><div class="card-top"><span class="badge">${e.end<date?'会期終了':e.start>date?'これから':'会期中'}</span><button class="favorite" data-fav="${e.id}" aria-label="${esc(e.title)}を${fav?'お気に入りから外す':'お気に入りに追加'}" aria-pressed="${fav}">${fav?'♥':'♡'}</button></div><h4>${esc(e.title)}</h4><p class="meta">${esc(e.museum)} / ${esc(e.region)}</p><p class="meta">${e.start.replaceAll('-','.')} — ${e.end.replaceAll('-','.')}</p>${r?`<p class="saved-note">${esc(r.date)} 鑑賞<br>${esc(r.note)}</p>`:''}<div class="actions"><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">公式案内を見る ↗</a><button data-record="${e.id}">${r?'記録を編集':'鑑賞を記録'}</button></div></article>`}).join('')}
for(const id of ['region','period','day','query','sort'])$('#'+id).addEventListener('input',render);
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;if(tab==='records')$('#period').value='all';document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));render()});
$('#grid').onclick=e=>{const f=e.target.closest('[data-fav]'),r=e.target.closest('[data-record]');if(f){const next=structuredClone(saved),id=f.dataset.fav;next.favorites=next.favorites.includes(id)?next.favorites.filter(x=>x!==id):[...next.favorites,id];persist(next)}if(r){editing=r.dataset.record;const record=saved.records[editing];$('#record-title').textContent=data.find(x=>x.id===editing).title;$('#visit-date').value=record?.date||today();$('#visit-date').max=today();$('#note').value=record?.note||'';$('#delete-record').hidden=!record;$('#editor').showModal()}};
$('#close').onclick=()=>$('#editor').close();$('#record-form').onsubmit=e=>{e.preventDefault();const next=structuredClone(saved);next.records[editing]={date:$('#visit-date').value,note:$('#note').value};if(persist(next)){$('#editor').close();toast('鑑賞記録を保存しました')}};$('#delete-record').onclick=()=>{if(!confirm('この鑑賞記録を削除しますか？'))return;const next=structuredClone(saved);delete next.records[editing];if(persist(next))$('#editor').close()};
$('#backup').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(saved,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='展覧手帖-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('#restore').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error();const x=JSON.parse(await file.text());if(!valid(x))throw Error();if(!confirm('このファイルの記録とお気に入りを、現在の手帖に追加します。同じ展覧会の記録は読み込む内容で置き換わります。'))return;const next={favorites:[...new Set([...saved.favorites,...x.favorites])],records:{...saved.records,...x.records}};if(persist(next))toast('手帖を読み込みました')}catch{toast('手帖のファイルを読み込めませんでした。')}finally{e.target.value=''}};render();
